require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MuSic' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNReactNativeGetMusicFiles', :path => '../node_modules/react-native-get-music-files'

  pod 'react-native-selectable-text', :path => '../node_modules/@astrocoders/react-native-selectable-text'

  pod 'react-native-get-music-files', :path => '../node_modules/react-native-get-music-files-v3dev-test'

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'MuSicTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end